// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type NewTrain struct {
	TrainNumber string `json:"train_number"`
	From        string `json:"From"`
	To          string `json:"To"`
	CoachNumber string `json:"Coach_number"`
	SeatNumber  int    `json:"Seat_number"`
	SeatType    string `json:"Seat_type"`
}

type NewUser struct {
	Name     string  `json:"Name"`
	Age      int     `json:"Age"`
	Email    string  `json:"Email"`
	Password *string `json:"Password"`
}

type Train struct {
	TrainNumber string `json:"train_number"`
	From        string `json:"From"`
	To          string `json:"To"`
	CoachNumber string `json:"Coach_number"`
	SeatNumber  int    `json:"Seat_number"`
	SeatType    string `json:"Seat_type"`
}

type TrainReserve struct {
	Book interface{} `json:"book"`
}

type User struct {
	Name     string `json:"Name"`
	Age      int    `json:"Age"`
	Email    string `json:"Email"`
	Password string `json:"Password"`
}
